spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mydb
    username: root
    password: Apple@27
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase :
    enabled: false

springdoc :
 swagger-ui :
  path : /swagger-ui.html
 api-docs :
  path : /api-docs
