spring:
  datasource:
    url: jdbc:mysql://mysql-service:3306/todo_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase :
    enabled: false

springdoc :
 swagger-ui :
  path : /swagger-ui.html
 api-docs :
  path : /api-docs

